### ISSUE TITLE
-webkit-fill-available as alias of stretch?

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#269] opened 2024-07-29 20:19 UTC
### What is the issue with the Compatibility Standard?

Firefox is shipping this, see: https://groups.google.com/a/mozilla.org/g/dev-platform/c/-pMSV-kgUjA/m/VRL09R1NAAAJ

**Comment by karlcow** [comment] 2024-07-29 22:39
Duplicate of #213

**Closed by karlcow** 2024-07-29 22:39 UTC
