### ISSUE TITLE
There is no definition for webkit-prefixed animation/transition event handlers

### ISSUE THREAD

**Issue by hiikezoe** [whatwg/compat#118] opened 2019-09-05 01:20 UTC
It would be nice to have it in the spec.

Unfortunately as of now, WebKit defines them in [Window](https://github.com/WebKit/webkit/blob/5cf2d3ed6657a12a51898d9bb0377aab0ef260a1/Source/WebCore/page/DOMWindow.idl#L198-L201) and [Element](https://github.com/WebKit/webkit/blob/8b95fadedc51b4dd26cfff21fe4cad6a78d84177/Source/WebCore/dom/Element.idl#L117-L120), Chrome defines them only in [Window](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/window.idl?l=206-210&rcl=7c99c02861f2916bd31d7e45a06d3a7846dc7479), Firefox defines them in [GlobalEventHandlers](https://searchfox.org/mozilla-central/rev/e5327b05c822cdac24e233afa37d72c0552dbbaf/dom/webidl/EventHandler.webidl#138-141) 

I've filed [a Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=999895) and [a Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1578121).

**Comment by karlcow** [comment] 2019-09-05 01:36
@hiikezoe I wonder if this is a duplicate of #59

**Comment by stephenmcgruer** [comment] 2019-09-05 13:07
Hi from Chromium :).

Because I was unaware that Firefox ships these, I actually just started down the road of investigating deprecating the prefix animation/transition event handlers. I have a [brief document](https://docs.google.com/document/d/16lUEgpgijfvXHQwz-IR2LQR936n-VcyTORNq6dd0jUg/edit) on the status. The most important part is probably the UseCounter data (for an overview on UseCounters see https://www.chromium.org/blink/platform-predictability/compat-tools):

- PrefixedAnimationEndEvent - 3.8%, and trending upwards (1.8% in September 2018).
- PrefixedAnimationIterationEvent - 0.002%, and approximately flat.
- PrefixedAnimationStartEvent - 0.1%, and approximately flat.
- PrefixedTransitionEndEvent - 3%, and approximately flat.

Based on that data, my intent was to try and deprecate PrefixedAnimationIterationEvent (filed a [Blink intent](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/EFazbHJRmnQ)), and then look at PrefixedAnimationStartEvent as the next lowest hanging fruit.

I would love to hear input from other browser vendors on what you think we should do. If the best route forward is to just compat-spec and test these, then that doesn't seem terrible to me (given that all major browsers ship them). And at that point we'd move them to GlobalEventHandlers to match the spec for the non-prefixed versions.

**Comment by stephenmcgruer** [comment] 2019-09-09 13:46
Just documenting for my future self, as I explore this space (working on [this nice demo](https://output.jsbin.com/siyenag/quiet)): it seems consistent across browsers that if an unprefixed `on{animation, transition}XXX` *and* a prefixed `onwebkit{animation, transition}XXX` are both registered, only the unprefixed version fires.

This appears to hold across latest Chrome, Firefox, Edge, and Safari stable releases.

**Comment by stephenmcgruer** [comment] 2019-09-13 15:45
I have a PR at https://github.com/whatwg/compat/pull/119, but it needs review by someone who reasonably understands the EventHandler spec to make sure I'm not accidentally spec-ing things that don't already exist today. If anyone has suggestions on who that person should be, I welcome them :)

**Comment by stephenmcgruer** [comment] 2019-09-16 12:37
Continuing to document for my future self; I'm not clear if any or all browsers support webkit-prefixed animation/transition events via `addEventListener('webkitFoo')`. I am playing with this at https://output.jsbin.com/gowejow/quiet, and Chrome appears to only fire `webkitAnimationStart` and
`webkitAnimationIteration` (cancel not tested). So no webkitAnimationEnd or any transition ones.

**Comment by miketaylr** [comment] 2019-09-17 01:22
> I have a PR at #119, but it needs review by someone who reasonably understands the EventHandler spec to make sure I'm not accidentally spec-ing things that don't already exist today. If anyone has suggestions on who that person should be, I welcome them :)

@annevk -- any suggestions?

**Comment by miketaylr** [comment] 2019-09-17 01:26
Hmm, wait. I think this is already in DOM: see Step 8 of invoke: https://dom.spec.whatwg.org/#concept-event-listener-invoke

Apologies for not getting to this earlier @stephenmcgruer. :(

**Comment by stephenmcgruer** [comment] 2019-09-17 13:05
No problem; I will take a look at that step and see if it covers the `onwebkit...` event handlers on `GlobalEventHandlers` or not.

cc @domenic who had stated their intent to review this post TPAC.

**Comment by annevk** [comment] 2019-09-18 02:28
It does not cover that, it only covers how to handle the special case during event dispatch.

@stephenmcgruer I'd recommend patching whatwg/html for the event handler attributes. Generally whatwg/compat is a last resort and ideally disappears long term as "base" specifications themselves ought to define prefixed variants.

**Comment by stephenmcgruer** [comment] 2019-09-26 11:35
@domenic Do you agree with annevk here?

**Comment by domenic** [comment] 2019-09-27 04:41
Yes, if we can patch the original specifications directly, that's ideal.

**Comment by stephenmcgruer** [comment] 2019-10-07 20:12
(Sorry for the delay, was away). Ack, will look into patching whatwg/html.

**Closed** 2020-01-09 16:41 UTC
